apiVersion: apps/v1
kind: Deployment
metadata:
  name: fantastic5-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fantastic5-app
  template:
    metadata:
      labels:
        app: fantastic5-app
    spec:
      serviceAccountName: fantastic-5-account
      containers:
      - name: fantastic-5-container
        image: public.ecr.aws/j4j2i5n9/fantastic-5-repo:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: fantastic5-service
  labels:
    app: fantastic5-app
spec:
  type: NodePort
  selector:
    app: fantastic5-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fantastic-5-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: fantastic5-service
            port:
              number: 80

